CREATE TABLE email_credentials
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    google_access_token VARCHAR(255)                            NOT NULL,
    google_expiry       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_emailcredentials PRIMARY KEY (id)
);