CREATE TABLE band
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    band_name         VARCHAR(100)                            NOT NULL,
    band_type         VARCHAR(255)                            NOT NULL,
    tribute_band_name VARCHAR(100),
    facebook_url      VARCHAR(255),
    instagram_url     VARCHAR(255),
    website_url       VARCHAR(255),
    CONSTRAINT pk_band PRIMARY KEY (id)
);

CREATE TABLE band_genres
(
    band_id BIGINT NOT NULL,
    genre   SMALLINT
);

CREATE TABLE band_youtube_video_ids
(
    band_id          BIGINT NOT NULL,
    youtube_video_id VARCHAR(255)
);

CREATE TABLE event
(
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_code                  VARCHAR(20)                             NOT NULL,
    band_id                     BIGINT                                  NOT NULL,
    venue_id                    BIGINT                                  NOT NULL,
    created_at                  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    email                       VARCHAR(255)                            NOT NULL,
    event_date                  date                                    NOT NULL,
    start_time                  time WITHOUT TIME ZONE                  NOT NULL,
    end_time                    time WITHOUT TIME ZONE                  NOT NULL,
    cover_charge                DOUBLE PRECISION                        NOT NULL,
    additional_info             VARCHAR(1000),
    event_creator               VARCHAR(255)                            NOT NULL,
    agrees_to_terms_and_privacy BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE venue
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    venue_name           VARCHAR(100)                            NOT NULL,
    address              VARCHAR(500)                            NOT NULL,
    latitude             DOUBLE PRECISION                        NOT NULL,
    longitude            DOUBLE PRECISION                        NOT NULL,
    county               VARCHAR(255)                            NOT NULL,
    town                 VARCHAR(255)                            NOT NULL,
    phone_number         VARCHAR(255),
    facebook_url         VARCHAR(255),
    instagram_url        VARCHAR(255),
    website_url          VARCHAR(255),
    CONSTRAINT pk_venue PRIMARY KEY (id)
);

ALTER TABLE event
    ADD CONSTRAINT uc_event_eventcode UNIQUE (event_code);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_BAND FOREIGN KEY (band_id) REFERENCES band (id);

ALTER TABLE event
    ADD CONSTRAINT FK_EVENT_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venue (id);

ALTER TABLE band_genres
    ADD CONSTRAINT fk_band_genres_on_band FOREIGN KEY (band_id) REFERENCES band (id);

ALTER TABLE band_youtube_video_ids
    ADD CONSTRAINT fk_band_youtube_video_ids_on_band FOREIGN KEY (band_id) REFERENCES band (id);