CREATE SEQUENCE IF NOT EXISTS bands_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS events_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS venues_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE band_genres
(
    band_id BIGINT NOT NULL,
    genre   VARCHAR(255)
);

CREATE TABLE band_youtube_ids
(
    band_id    BIGINT NOT NULL,
    youtube_id VARCHAR(255)
);

CREATE TABLE bands
(
    id                BIGINT NOT NULL,
    name              VARCHAR(255),
    band_type         VARCHAR(255),
    tribute_band_name VARCHAR(255),
    facebook_url      VARCHAR(255),
    instagram_url     VARCHAR(255),
    website_url       VARCHAR(255),
    CONSTRAINT pk_bands PRIMARY KEY (id)
);

CREATE TABLE email_credentials
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    google_access_token VARCHAR(255)                            NOT NULL,
    google_expiry       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_emailcredentials PRIMARY KEY (id)
);

CREATE TABLE event_bands
(
    band_id  BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_event_bands PRIMARY KEY (band_id, event_id)
);

CREATE TABLE events
(
    id             BIGINT NOT NULL,
    venue_id       BIGINT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    creator_type   VARCHAR(255),
    start_time     TIMESTAMP WITHOUT TIME ZONE,
    end_time       TIMESTAMP WITHOUT TIME ZONE,
    event_url      VARCHAR(255),
    event_email    VARCHAR(255),
    event_phone    VARCHAR(255),
    event_page_id  VARCHAR(255),
    email_sent     BOOLEAN,
    terms_accepted BOOLEAN,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE venues
(
    id            BIGINT       NOT NULL,
    name          VARCHAR(255) NOT NULL,
    address       VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    venue_phone   VARCHAR(255) NOT NULL,
    lat           DOUBLE PRECISION,
    lon           DOUBLE PRECISION,
    county        VARCHAR(255),
    place_id      VARCHAR(255),
    town          VARCHAR(255),
    facebook_url  VARCHAR(255),
    instagram_url VARCHAR(255),
    website_url   VARCHAR(255),
    CONSTRAINT pk_venues PRIMARY KEY (id)
);

ALTER TABLE venues
    ADD CONSTRAINT uc_venues_address UNIQUE (address);

ALTER TABLE venues
    ADD CONSTRAINT uc_venues_name UNIQUE (name);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venues (id);

ALTER TABLE band_genres
    ADD CONSTRAINT fk_band_genres_on_band FOREIGN KEY (band_id) REFERENCES bands (id);

ALTER TABLE band_youtube_ids
    ADD CONSTRAINT fk_band_youtube_ids_on_band FOREIGN KEY (band_id) REFERENCES bands (id);

ALTER TABLE event_bands
    ADD CONSTRAINT fk_eveban_on_band FOREIGN KEY (band_id) REFERENCES bands (id);

ALTER TABLE event_bands
    ADD CONSTRAINT fk_eveban_on_event FOREIGN KEY (event_id) REFERENCES events (id);